<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.potato</groupId>
		<artifactId>potato</artifactId>
		<version>1.0.0</version>
	</parent>

	<groupId>org.potato</groupId>
	<artifactId>potato-jdbc</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>
	
	<name>potato-jdbc</name>
	<description>potato-jdbc</description>
	<url>http://maven.apache.org</url>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<!-- Potato -->
		<dependency>
			<groupId>org.potato</groupId>
			<artifactId>potato-util-db</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.potato</groupId>
			<artifactId>potato-util-web</artifactId>
			<version>1.0.0</version>
		</dependency>
		<!-- Spring -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<!-- Jackson JSON -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<!-- JSqlParser -->
		<dependency>
			<groupId>com.github.jsqlparser</groupId>
			<artifactId>jsqlparser</artifactId>
		</dependency>
		<!-- Apache Log4j -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
		</dependency>
		<!-- Database Driver -->
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>
	</dependencies>
</project>



