<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.potato</groupId>
		<artifactId>potato</artifactId>
		<version>3.0.0</version>
	</parent>

	<groupId>org.potato</groupId>
	<artifactId>potato-all</artifactId>
	<version>3.0.0</version>
	<packaging>jar</packaging>
	
	<name>potato-all</name>
	<description>You just need to import this dependency for your project</description>
	<url>http://maven.apache.org</url>

	<properties>
		<java.version>17</java.version>
	</properties>

	<dependencies>
		<!-- All Potato -->
		<dependency>
			<groupId>org.potato</groupId>
			<artifactId>potato-jdbc</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.potato</groupId>
			<artifactId>potato-security</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.potato</groupId>
			<artifactId>potato-validation</artifactId>
			<version>3.0.0</version>
		</dependency>
	</dependencies>
</project>



